baseURL = 'https://cometvisu.github.io/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'CometVisu - Smarthome Visualization'

[params]
  description = "Flexible, customizable smarthome visualization for KNX, OpenHAB and more"
  author = "CometVisu Team"
  githubRepo = "https://github.com/CometVisu/CometVisu"
  # Version path depends on CometVisu submodule branch: "latest" for master, "develop" for develop
  versionPath = "develop"
  docsBaseUrl = "https://www.cometvisu.org/CometVisu"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "CometVisu - Smarthome Visualization"
    [languages.en.params]
      description = "Flexible, customizable smarthome visualization for KNX, OpenHAB and more"
  [languages.de]
    languageName = "Deutsch"
    weight = 2
    title = "CometVisu - Smarthome Visualisierung"
    [languages.de.params]
      description = "Flexible, anpassbare Smarthome-Visualisierung f√ºr KNX, OpenHAB und mehr"

[menu]
  [[menu.main]]
    name = "Features"
    url = "#features"
    weight = 1
  [[menu.main]]
    name = "Anpassung"
    url = "#customization"
    weight = 2
  [[menu.main]]
    name = "Demo"
    url = "#demo"
    weight = 3
  [[menu.main]]
    name = "Dokumentation"
    url = "https://www.cometvisu.org/CometVisu/de/latest/manual"
    weight = 4
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/CometVisu/CometVisu"
    weight = 5

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
